spring.application.name=code-learning-platform

# render has their own port
server.port = ${PORT:8080}

# spring profile default = local
spring.profiles.active=${SPRING_PROFILE_ACTIVE:local}

# database - supabase postgresql
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
springdatasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
# When your Spring Boot app starts, Hibernate looks at all your @Entity classes and compares them against the actual tables in your database and checks if they match.
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true;

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000
jwt.refresh-expiration=604800000

# CORS
cors-allowed-origins=${CORS_ORIGINS:http://localhost:3000}

#LOGGING
logging.level.org.springframework.security=DEBUG
logging.level.com.Technick_code.code_learning_platform=DEBUG